version: "3.9"

services:
  caddy:
    image: caddy:2.5.1-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
      - ./frontend:/frontend

  keystone:
    image: ghcr.io/stjj-de/backend:latest
    restart: unless-stopped
    env_file:
      - "./config/keystone.env"
    volumes:
      - ./data/keystone:/app/data
      - /etc/timezone:/etc/timezone

  umami:
    image: ghcr.io/mikecao/umami:mysql-latest
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql://umami:umami@umami_db:3306/umami
      DATABASE_TYPE: mysql
    env_file:
      - "./config/umami.env"
    depends_on:
      - umami_db

  umami_db:
    image: mariadb:10.8.3
    restart: unless-stopped
    environment:
      MARIADB_USER: umami
      MARIADB_PASSWORD: umami
      MARIADB_DATABASE: umami
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes # only accessible from localhost anyway

    volumes:
      - ./static/umami-schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./data/umami:/var/lib/postgresql/data

