version: "3.9"

services:
  caddy:
    image: caddy:2.5.1-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
      - ./frontend:/frontend
    depends_on:
      - keystone

  keystone:
    image: ghcr.io/stjj-de/backend:latest
    restart: unless-stopped
    env_file:
      - "./config/keystone.env"
    volumes:
      - ./data:/app/data
      - /etc/timezone:/etc/timezone
