version: "3.8"
services:
  caddy:
    image: caddy:2.4.6-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
    depends_on:
      - strapi

  strapi:
    build: https://github.com/stjj-de/backend.git
    restart: always
    environment:
      HOST: 0.0.0.0
      PORT: 1337
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    env_file:
      - "./config/strapi.env"
    volumes:
      - ./data/uploads:/app/public/uploads
      - /etc/timezone:/etc/timezone
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
